product_list:
  path: /list
  methods: GET
  controller: App\Controller\ProductController::getProductList

product_get:
  path: /get/{id}
  methods: GET
  controller: App\Controller\ProductController::getProduct
  requirements:
      page: '\d+'

product_add:
  path: /add
  methods: POST
  controller: App\Controller\ProductController::addProduct

product_edit:
  path: /edit/{id}
  methods: PUT
  controller: App\Controller\ProductController::editProduct
  requirements:
          page: '\d+'